### ISSUE TITLE
请问图片里的三个函数分别是那里的？

### ISSUE THREAD

**Issue by michaelnbk** [JimnSu/ignav#2]
正在学习您的代码，编译时遇到这个问题：
![Screenshot from 2020-04-30 17^%35^%29](https://user-images.githubusercontent.com/20315245/80696561-2383de80-8b0a-11ea-88ff-d7760fca78bc.png)

**Comment by rj-sujinglan** [comment]
norm_distri()，resize()和avg在rtkcmn.cc，其他几个函数没有用到，可以注释掉，或者直接用这个工程：https://github.com/Erensu/carvig

**Comment by michaelnbk** [comment]
谢谢你的回复，carvig里有这三个函数，但在ignav里貌似没有
